### PR TITLE
Add nominal support for zabbix v 4.0

### PR DESCRIPTION
**Pull request by svdasein**
This just slaps 4.0 in the list of supported versions. I've not tested it beyond my immediate needs but it works well enough for me.

### CODE REVIEW

**Comment by gdubicki** [comment]
See also https://github.com/express42/zabbixapi/pull/85#issuecomment-412325881.

**Comment by gdubicki** [comment]
In 4.0 a few deprecated in 3.4 API methods have been removed:
```
ZBXNEXT-4247 | removed deprecated API methods: user.updareProfile, user.addMedia, user.updateMedia, user.deleteMedia, usergroup.massAdd, usergroup.massUpdate and usermedia.get
```
Sources:
* https://www.zabbix.com/rn/rn3.4.0alpha1
* https://www.zabbix.com/rn/rn4.0.0alpha1
* https://support.zabbix.com/browse/ZBXNEXT-4247

**Comment by gdubicki** [comment]
Above methods are used here in this lib:
* https://github.com/express42/zabbixapi/blob/master/lib/zabbixapi/classes/usergroups.rb#L48
* https://github.com/express42/zabbixapi/blob/master/lib/zabbixapi/classes/usergroups.rb#L65
* https://github.com/express42/zabbixapi/blob/master/lib/zabbixapi/classes/users.rb#L37
* https://github.com/express42/zabbixapi/blob/master/lib/zabbixapi/classes/users.rb#L54

**Comment by gdubicki** [comment]
I suggest to remove those 4 methods in this PR (can you, @svdasein ?) and release this library as 4.0.0 (it seems that its version is synchronized with Zabbix) stating in the changelog that some unsupported in 4.0.0 methods have been dropped.

What do you think about this approach, @lehn-etracker ?

**Comment by gdubicki** [comment]
@aladmit , maybe you can reply to my proposal above?

**Comment by aladmit** [comment]
@gdubicki Sounds great for me, but I don`t maintain this project anymore.

If you want to realize this approach and support it, I`ll give all permissions for that.

**Comment by baurmatt** [comment]
@svdasein Could you please include the suggested change of @gdubicki? Would love to see this merged/released! :)

**Comment by svdasein** [comment]
I'm not the project maintainer - I can't merge anything.  Also re: excluding methods - I'm not sure the right approach is to just delete them - there's probably some version checking logic that needs to go in. Again though I'm not the maintainer.  I just did that one stupid little hack.

**Comment by gdubicki** [comment]
@aladmit : so can you please give me maintainer permissions?

**Comment by aladmit** [comment]
@gdubicki Done!

**Comment by gdubicki** [comment]
Let's add the overdue support for 4.0 for now. I will work on cleaning up non-working methods in a minor update within a few days.

**Pull request merged**
