### PR TITLE
Remove dependency version lockdown of JSON gem

### PR DESCRIPTION
**Pull request by taharah**

### CODE REVIEW

**Comment by evtuhovich** [comment]
@taharah i'm not sure, that zabbixapi works with all json gem versions, i prefer to set gem versions explicitly.

**Comment by taharah** [comment]
I submitted the PR since I run into issues from time to time since whenever I install JSON 2.x I start getting gem dependency failures.

**Comment by jrbeilke** [comment]
Yea in order to support Ruby < 2.X we need the json gem to be < 2.X unless we drop support for older versions of Ruby.

Should probably update the dependency to use json 1.8.X so we get the latest performance and security fixes while still supporting Ruby 1.9

**Comment by taharah** [comment]
Ah OK if the intention is to support Ruby <2.0 then I'll update the PR to at least be for the latest 1.x JSON gem.

**Comment by postgred** [comment]
@jrbeilke Why we should support ruby <2?

**Comment by atheiman** [comment]
i think this can be closed in favor of #65

**Pull request closed without merging**
